name: desktop_window_manager
description: Get Windows information on your desktop and control it.
version: 1.0.0
homepage: https://github.com/stacew/desktop_window_manager.git

environment:
  sdk: ">=2.18.2 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  win32: ^3.0.1
  bitmap: ^0.1.2
  ffi: ^1.0.0
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      linux:
        pluginClass: DesktopWindowManagerPlugin
      macos:
        pluginClass: DesktopWindowManagerPlugin
      windows:
        pluginClass: DesktopWindowManagerPluginCApi
