name: desktop_window_manager
description: |
  Get Windows information on your desktop and control it.
  getTitle, getIconMemory, getModuleName, getPath,
  setAlwaysOn, setOpacity, setDisabled, setMinimized,

version: 2.0.0
homepage: https://github.com/stacew/desktop_window_manager.git

environment:
  sdk: ">=2.18.2 <3.0.0"
  flutter: ">=2.5.0"

# flutter packages pub publish --dry-run
dependencies:
  win32: ^3.0.1

  ffi: ^2.0.1
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      linux:
        pluginClass: DesktopWindowManagerPlugin
      macos:
        pluginClass: DesktopWindowManagerPlugin
      windows:
        pluginClass: DesktopWindowManagerPluginCApi
